### ISSUE TITLE
hexo g时报错

### ISSUE THREAD

**Issue by traddo** [lotabout/very-simple#27]
ERROR TypeError: /home/blog/themes/very-simple/layout/archive.jade:34
    32|         .post-archive
    33|             //Use lodash to classify posts. See https://lodash.com/docs#groupBy
  > 34|             each posts, year in _.groupBy(page.posts.toArray(), function(p){return -p.date.format('YYYY')})
    35|               h2= -year
    36|               ul.listing
    37|                 for post in posts

Cannot read property 'groupBy' of undefined
    at eval (eval at exports.compile (/home/blog/node_modules/jade/lib/index.js:218:8), <anonymous>:594:17)
    at eval (eval at exports.compile (/home/blog/node_modules/jade/lib/index.js:218:8), <anonymous>:774:4)
    at eval (eval at exports.compile (/home/blog/node_modules/jade/lib/index.js:218:8), <anonymous>:986:22)
    at res (/home/blog/node_modules/jade/lib/index.js:219:38)
    at _View._compiled (/home/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/home/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /home/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/home/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:481:10)
    at resume_ (_stream_readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: '/home/blog/themes/very-simple/layout/archive.jade'
}

**Comment by 0914ds** [comment]
i have the same issue, anybody can fix it?

**Comment by dyj888777** [comment]
本是同根生，相煎何太急，sorry，888777b.com（大赢家策略论坛）
